### ISSUE TITLE
Fail to fetch "NIST Research Library (2022)"

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-nist#109]
The doc isn't available anymore.

**Comment by ronaldtse** [comment]
This is supposed to be a static entry.

**Comment by andrew2net** [comment]
@ronaldtse this is not a static file. The GHA failed because a contributor without a surname node appeared. For some reason, I stopped getting GHA error notifications from the relaton-data-nist repo. I need to find out how to restore the notifications.

**Comment by ronaldtse** [comment]
Hmmm, this is a static file...:
* https://github.com/relaton/relaton-data-nist/blob/main/static/NIST_Research_Library_2023.yaml

But anyway the bug is at relaton-nist and fixed. Thanks.

**Comment by andrew2net** [comment]
@ronaldtse you are right, they are static. But the GHA failed and didn't add the static files and some other NIST docs.
