### ISSUE TITLE
URL in README leads to a 404 error 

### ISSUE THREAD

**Issue by tward212** [relaton/relaton-nist#114]
Under "Fetch data" in the README, clicking the URL provided (https://raw.githubusercontent.com/usnistgov/NIST-Tech-Pubs/nist-pages/xml/allrecords.xml ) results in a 404 error. This appears to be related to the allrecords dataset change mentioned in #112.

Excerpt from README
> 
> Fetch data
> 
> This gem uses the https://raw.githubusercontent.com/usnistgov/NIST-Tech-Pubs/nist-pages/xml/allrecords.xml dataset as one of data sources.

**Comment by ronaldtse** [comment]
The README has been refactored in #115 and the problem should be resolved.

Thanks @tward212 for the report!
