### ISSUE TITLE
Add place of publication

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-nist#31]
Because of https://github.com/metanorma/metanorma-ogc/issues/46, please add `<place>Gaithersburg, MD</place>` to all records generated by Relaton (in the right place in the XML, of course.)

**Comment by ronaldtse** [comment]
We should probably use the full address of NIST then. Can we store the address in some YAML file in the gem so it’s easily editable? Thanks.

**Comment by opoudjis** [comment]
This needs to be clarified:

`place` contains only the city of publication.

`contributor/organization/address` is where any full address for NIST would go. And (a) we have not come up with a format for that yet (so just put the address in with `<br/>` for now; (b) eventually we will need to vary the address: FIPS documents come from a different address.

**Comment by ronaldtse** [comment]
@opoudjis I am against encoding city ("place") separately with the address. The "city" is an element of the address. It should just be encoded as an address.

**Comment by opoudjis** [comment]
No. You are not going to change the Relaton model now, and you are not going to contravene centuries of bibliographic practice. The place of publication in bibliographies is always a city and NEVER an address.

**Comment by ronaldtse** [comment]
@opoudjis In ISO 690, the "place" stands for the "place of publication" i.e. "address of the publisher". It is also clear that bibliographic entries have "place" just as the city name, and all sorts of qualified city names (i.e. "Paris", "Paris, TX", "Paris, Texas", "Paris, TX, USA" etc).

Here are examples from Springer:
https://www.springer.com/engineering?SGWID=0-175-6-791930-0

## Qualified to US State

"Itho K, Hayashi T, Muramoto A, Miyakawa M (1997) Controllability of temporomandibular joint loading by masculation: an analysis using a two-dimension static model incorporating a spring mode of the articular disk. In: Jeager R, Agarwal G, Mykleburst B, Feinberg B (eds) Proceedings of the 19th International Conference of the IEEE Engineering in Medicine and Biology Society, Chicago, Part 4 of 6, IEEE Service Center, Piscataway, NJ, pp1847-1848. Also available from CD-ROM, #85"

## Qualified to country

"Dekker LRC (1996) Role of intracellular calcium in ischemic damage and preconditioning in cardiac muscle. PhD Thesis, University of Amsterdam, Amsterdam, The Netherlands"

## Multiple places are allowed.

"Hovind HJ (1986) Traumatic birth injuries. In: Raimondi AJ, Choux M, Di Rocco C (eds) Head Injuries in the Newborn and Infant. Principles of Pediatric Neurosurgery, Springer, Berlin Heidelberg New York, pp 87–109"

**Comment by opoudjis** [comment]
... Eh?

Place is not address of the publisher in ISO 690, or in any bibliographic system, and your examples confirm that. They are only the city of publication, optionally with a state or country qualifier, and optionally with multiple cities.

Obviously a city of publication is NOT the address of the publisher: the street name and number of the publisher NEVER appears in the place of publication, and the state and country appear only rarely for disambiguation.

Which means I am right, and your examples prove I am right. place of publication is distinct from the address; and because the state/country disambiguation is context-specific, it is also distinct from the city field of the address.

**Comment by ronaldtse** [comment]
In ISO 690, the “place” is called “place of publication”, and that is where the work is published. A place that can be described IS an address with resolution bound to the city-level.

**Comment by ronaldtse** [comment]
And the “multiple places” example directly contradict this. Multiple cities mean that the work is published simultaneously at multiple places. It is not meant to be a free form entry.

**Comment by ronaldtse** [comment]
> state/country disambiguation is context-specific

A bibliographic item CANNOT be context-specific. Its rendering CAN be. Therefore in the encoding it CANNOT be context-specific.

**Comment by opoudjis** [comment]
We're going to have to discuss this, because I don't see anything you say as contradicting my assertion that the place of publication cannot be extracted from an address.

**Comment by opoudjis** [comment]
We're in agreement: data taken from address to populate place, but parameter needed to localise how many address fields are used to generate place.

**Comment by ronaldtse** [comment]
@opoudjis since we now have a definitive form from 690, perhaps this is applicable to all MN flavors, not only OGC?

**Comment by opoudjis** [comment]
The current implementation of rendering is ad hoc, and any true implementation of bibliographic rendering is going to be (a) a monstrously large piece of work, and (b) an inexcusable waste of time, given that standards documents cite non-standards so little.

Way premature to generalise this.
