### ISSUE TITLE
Support fetching documents using NIST MR code

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#49]
Relaton NIST should support fetching documents using the NIST MR code, specified here:

https://github.com/metanorma/metanorma-nist/issues/168

**Comment by ronaldtse** [comment]
@andrew2net says the feed mostly works, except for the "update" action. Can you elaborate here? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse the "nist-mr" identifier uses dot as a delimiter but NIST identifiers often has vesion number with dots. Foe examle what would the "NIST SP 800-63 Ver. 1.0.2" identifier be in the "nist-mr" format?

**Comment by ronaldtse** [comment]
@andrew2net good question. How about we replace the '.' in the Ver with '-'? We will have to update documentation.

**Comment by andrew2net** [comment]
@ronaldtse I think we coudl use Regex to extract version with dots in it's value from an identifier. So we can use identifiers like "NIST.SP.800-63.ver.1.0.2"

**Comment by ronaldtse** [comment]
We must stick to the defined NIST MR syntax (metanorma/metanorma-nist#168). So the code has to be:

* NIST.SP.800-63.ver1-0-2 (`v` stands for "volume", `ver` is version)
* NIST SP 800-38A Addendum => NIST.SP.800-38A.pt-A.add-1 (the `add` part is new to NIST MR)
