### ISSUE TITLE
Describe how to specify "revision" and "addendum" in identifier for search in README

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#50]
* "SP 800-67r2" should be expressed as "SP 800-67 Rev. 2"
* "SP 800-38Ar3" should be expressed as "SP 800-38A Rev. 3"

And the addendum:
* "SP 800-38A Addendum" (#48)

**Comment by ronaldtse** [comment]
Confirmed fixed. Thanks @andrew2net !

**Comment by andrew2net** [comment]
@ronaldtse please pay attention that `NIST SP 800-40r3` isn't a revision 3 `Rev. 3`. It's a reference with document number `800-40r3` and should be fetched by the "NIST SP 800-40r3" reference.
Searching by reference `SP 800-67r2` on the NIST site doesn't give a result. There is only `SP 800-67 Rev. 1` and `SP 800-67 Rev.2`.
To reduce misunderstanding I'll change search specific revision from `SP 800-67 r2` to `SP 800-67 Rev. 2`.

**Comment by ronaldtse** [comment]
?? 800-40r3 Exactly means Rev. 3.

**Comment by ronaldtse** [comment]
800-40r3 is indeed Revision 3:  https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-40r3.pdf

Ie. 800-40r3 and 800-40 Rev. 3 are just different ways of referring to the same document.
