### ISSUE TITLE
`NBS IR 87-363` contains "error:"

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-nist#54]
`NBS IR 87-363` contains "error:" Maybe NIST should know about it?

```xml
<publisher>
   <publisher_name>error:</publisher_name>
   <publisher_place>Gaithersburg, MD</publisher_place>
</publisher>
<institution>
   <institution_name>error:</institution_name>
   <institution_acronym>error:</institution_acronym>
   <institution_place>Gaithersburg, MD</institution_place>
</institution>
```

_Originally posted by @andrew2net in https://github.com/relaton/relaton-nist/issues/53#issuecomment-883321348_

**Comment by ronaldtse** [comment]
Reported to NIST via ticket and email.

**Comment by ronaldtse** [comment]
Kathryn Miller of NIST ISO has replied and is looking at this.

**Comment by ronaldtse** [comment]
@andrew2net this is fixed in the source data, https://github.com/usnistgov/NIST-Tech-Pubs/issues/2 . Closing.
