### ISSUE TITLE
Move NIST Tech Pubs fetcher.rb into relaton-nist gem

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#60]
This is to move the `fetcher.rb` script in relaton-data-nist into the Relaton gem framework to support this:

```sh
$ gem install relaton-nist
$ relaton fetch-data nist-tech-pubs -o data/ -f yaml
```

Gets a directory `data/` filled with Relaton XML/YAML files from the NIST Tech Pubs file (allrecords.xml).

**Comment by andrew2net** [comment]
@ronaldtse The command name `relaton` is used by the `relaton-cli` already. Do we really need to involve `relaton-cli` here?
Maybe we can use just `fetch-nist-data -o data/ -f yaml`?
