### ISSUE TITLE
Provide bibliographic item for citing the whole data series

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#68]
https://github.com/usnistgov/NIST-Tech-Pubs/blob/a036714cc754d08ef5448b762ceb9e618b6115bb/xml/readme.txt#L48-L50

```
Recommended citation for the data:

NIST Research Library (2022) NIST Technical Series Publication Metadata. (National Institute of Standards and Technology, Gaithersburg, MD) https://doi.org/10.18434/M32192
```

**Comment by andrew2net** [comment]
@ronaldtse I'm unable to get what we need to do here.

**Comment by ronaldtse** [comment]
We need to create a bibliographic item that is for the whole "NIST Research Library (2022)". This will be a statically managed item.

**Comment by andrew2net** [comment]
File is added https://github.com/relaton/relaton-data-nist/blob/main/data/NIST_RESEARCH_LIBRARY_(2022).yaml

**Comment by andrew2net** [comment]
The document can be fetch using relaton-nist v1.16.3
```sh
$ relaton fetch "NIST Research Library (2022)"
[relaton-nist] (NIST Research Library) fetching...
[relaton-nist] (NIST Research Library) found `NIST Research Library (2022)`
<bibdata type="standard" schema-version="v1.2.4">
...
```

**Comment by ronaldtse** [comment]
@andrew2net can you please add this to the README? Thanks.

**Comment by ronaldtse** [comment]
> The document can be fetch using relaton-nist v1.16.3
> 
> ```shell
> $ relaton fetch "NIST Research Library (2022)"
> [relaton-nist] (NIST Research Library) fetching...
> [relaton-nist] (NIST Research Library) found `NIST Research Library (2022)`
> <bibdata type="standard" schema-version="v1.2.4">
> ...
> ```

Also, the "NIST Research Library" is now in 2023, we should support that.

**Comment by andrew2net** [comment]
> @andrew2net can you please add this to the README? Thanks.

Do we really need to add references to the README? I think we will finally have all the references on GH pages.

**Comment by ronaldtse** [comment]
> Do we really need to add references to the README? I think we will finally have all the references on GH pages.

Good point, yes the GH Pages would work better.

**Comment by andrew2net** [comment]
> Also, the "NIST Research Library" is now in 2023, we should support that.

I got the metadata for 2022 from https://data.nist.gov/od/id/mds2-2192, but not sure if it is correct. I didn't find any other "NIST Research Library" page. Is it a good link for both 2022 and 2023 publications? Or we should links to the NIST-Tech-Pubs/xml/readme.txt in git commits?
