### ISSUE TITLE
(URGENT) Broken data for CSWP

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#75]
From @strogonoff at https://github.com/ietf-ribose/bibxml-service/issues/134#issuecomment-1165234822

CSWPs are named by identifiers, not sequential IDs.

CSWP identifiers are possibly wrong.

> For example, NIST CSWP 02122014—https://github.com/relaton/relaton-data-nist/tree/main/data/NIST_CSWP_02122014.yaml doesn’t exist, but we have https://github.com/relaton/relaton-data-nist/blob/b7042a5293b203037be1ca11ced9fbf5aa2a71cf/data/NIST_CSWP_1.yaml that has an external link to 02122014 (?).
> 
> Got errors for other CSWP identifiers, too (NIST CSWP 01262018, NIST CSWP 06032014, etc.).

**Comment by andrew2net** [comment]
@ronaldtse in the dataset https://raw.githubusercontent.com/usnistgov/NIST-Tech-Pubs/nist-pages/xml/allrecords.xml the documents with the external links have identifiers `NIST CSWP 1`, `NIST CSWP 5`, `NIST CSWP 3`, etc.
Should we replace numbers in all the `NIST CSWP *` identifiers with numbers from the DOI external links?

**Comment by ronaldtse** [comment]
Oh my -- NIST has implemented the fix we suggested! All CSWPs now are numbered sequentially.

@andrew2net and @strogonoff, so this the correct data now. Look at CSWP 1, the DOI is `CSWP.1`. This is definitely intentional.

So we will need to map the CSWPs from the old identifiers to the new ones.

**Comment by andrew2net** [comment]
@ronaldtse should we implement an index to map the old identifiers?

**Comment by ronaldtse** [comment]
@andrew2net no, we just stay with the new identifiers. If the authoritative data source has updated identifiers, we only use those.

**Comment by andrew2net** [comment]
@ronaldtse so, can we close this issue?

**Comment by ronaldtse** [comment]
Closed.
