### ISSUE TITLE
"NISTIR" full series name is "NIST IR (Interagency/Internal Reports)", not "NIST NISTIRs (Interagency/Internal Reports)"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#81]
https://github.com/relaton/relaton-data-nist/blob/be0db992090a37c5eb48c12ef60582d1c93215cb/data/NISTIR_90-4250.yaml#L56-L60

"NISTIR" full series name is "NIST IR (Interagency/Internal Reports)", not "NIST NISTIRs (Interagency/Internal Reports)".

**Comment by andrew2net** [comment]
fixed https://github.com/relaton/relaton-data-nist/blob/172ece9ac799452f3c21d9da2a4b13c5f9cad9eb/data/NISTIR_90-4250.yaml#L58
