### ISSUE TITLE
(URGENT) Structural discrepancies in Relaton-NIST data files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#83]
From https://github.com/relaton/relaton/issues/108

There are structural discrepancies reported by @strogonoff.

>  * [NIST](https://raw.githubusercontent.com/ietf-tools/relaton-data-nist/main/data/NBS_BH_1.yaml):
> 
> ```
> contributor -> 8 -> organization -> abbreviation
>   str type expected (type=type_error.str)
> ```

**Comment by andrew2net** [comment]
@ronaldtse since we dropped simplifying the YAML output, the abbreviation is rendered as an object.
As @strogonoff said the bixml-service is adopted to consume the objects.
