### ISSUE TITLE
Empty string for `relation.type`

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-nist#84]
We’re getting an issue with [empty `relation.type`](https://github.com/ietf-tools/relaton-data-nist/blob/f9ecbf1f23085117f0ddbfaee7e526de90d3a53f/data/NIST_SP_1273-DRAFT.yaml#L59) in some items.

1. YAML parser (presumably by design) interprets empty property value as None, which breaks deserializer that suddenly encounters an incompatible data type (in relaton-py bibdata deserializer, `relation.type` is not optional and expected to be a string).
2. `relation.type` probably shouldn’t be empty because Relaton spec [doesn’t seem to allow](https://github.com/relaton/relaton-models/blob/cca170ccf935d89697282df31bbdb8d1ef2290c6/grammars/biblio.rnc#L497) this.

**Comment by andrew2net** [comment]
@strogonoff there is relations' types mapping which doesn't have a newly added relation type. In such cases the relaton-nist logs warning `Relation type {relation-type} not found`.
I've added the new "isPreprintOf" type mapping in v 1.14.1

**Comment by andrew2net** [comment]
fixed https://github.com/ietf-tools/relaton-data-nist/blob/245fca8ae8f7fc1eefb05c3ca356657a77cca698/data/NIST_SP_1273-DRAFT.yaml#L59

**Comment by ronaldtse** [comment]
> @strogonoff there is relations' types mapping which doesn't have a newly added relation type. In such cases the relaton-nist logs warning `Relation type {relation-type} not found`.
> I've added the new "isPreprintOf" type mapping in v 1.14.1

@andrew2net can you confirm that `isPreprintOf` is documented on relaton.org? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse I've checked and find out that we don't have `isPreprintOf` in the grammar. Ping @opoudjis

**Comment by ronaldtse** [comment]
@andrew2net for model enhancements please directly file into https://github.com/relaton/relaton-models/issues/ . Thanks.

**Comment by ronaldtse** [comment]
@andrew2net the other ticket has concluded with this:
https://github.com/relaton/relaton-models/issues/48#issuecomment-1689818790

Please use DocumentRelationType.hasDraft and DocumentStatus.stage to represent a "preprint".

**Comment by andrew2net** [comment]
done https://github.com/relaton/relaton-data-nist/blob/a8be95eedebd80609096615ab5589ac951a68cc2/data/NIST_SP_1273-DRAFT.yaml#L58-L71

**Comment by ronaldtse** [comment]
Thank you @andrew2net !
