### ISSUE TITLE
Missing `abstract.content`

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-nist#85]
Example: https://github.com/ietf-tools/relaton-data-nist/blob/f9ecbf1f23085117f0ddbfaee7e526de90d3a53f/data/NIST_TN_2207-UPD1.yaml#L57-L60

I believe [according to the grammar](https://github.com/relaton/relaton-models/blob/cca170ccf935d89697282df31bbdb8d1ef2290c6/grammars/biblio.rnc#L421) as a formatted string abstract should have `content`.

**Comment by andrew2net** [comment]
fixed https://github.com/ietf-tools/relaton-data-nist/blob/main/data/NIST_TN_2207-UPD1.yaml
