### ISSUE TITLE
Document where document metadata comes from (different sources)

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-nist#92]
* Most NIST Tech Pubs data come from https://github.com/usnistgov/NIST-Tech-Pubs/
* All publications from the Computer Security Division of the Information Technology Lab come from the Metanorma endpoint (https://github.com/relaton/relaton-nist/blob/a905f66386bc004fd874225b5817fa280a05ade5/lib/relaton_nist/pubs_export.rb#L6) of the CSRC (http://csrc.nist.gov/), including
  * SP 800-*
  * SP 1800-*
  * CSWP
  * etc. (we need to document them all)

We need to add this description to the README and the public site.

**Comment by andrew2net** [comment]
@ronaldtse is this that we need https://github.com/relaton/relaton-nist#data-sources

**Comment by ronaldtse** [comment]
Yes you're correct. Thanks!
